---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-space
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins-space
  #annotations:
  #  eks.amazonaws.com/role-arn: arn:aws:iam::895533345638:role/jenkins-role
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: jenkins-space
  annotations:
    kubernetes.io/service-account.name: jenkins-admin
type: kubernetes.io/service-account-token
---
