apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: jenkins-nc
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
    #- id: ami-00beaa403aa4a673d #amazon-linux amd64 comatible with eks-1.32
  userData: |
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          registryPullQPS: 50
          registryBurst: 100
  subnetSelectorTerms:
    - tags:
        Type: staple-nvirginia-vpc-private
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: dev-staple-cluster
  role: "dev-staple-worker-role"
  tags:
    worktype: nonprod
    env: dev
    karpenter.sh/managed-by: dev-staple-cluster
    team: backend
    Name: karpenter-dev-jenkins
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  # Optional, configures detailed monitoring for the instance
  # detailedMonitoring: true
